name: Deploy to Vercel (Web frontend)

on:
  push:
    branches:
      - main
    paths:
      - "packages/web/**"
      - ".github/workflows/web-deploy.yml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-args: '--prod'
          working-directory: packages/web
      - name: "Install dependencies"
        run: "npm install"
      - name: "Build"
        run: "npm build"