name: Deploy to Vercel (Web frontend)

on:
  push:
    branches:
      - main
    paths:
      - "packages/web/**"
      - ".github/workflows/web-deploy.yml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./packages/web
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          working-directory: ./packages/web