name: Deploy to Vercel (Web frontend)

on:
  push:
    branches:
      - main
    paths:
      - "packages/web/**"
      - ".github/workflows/web-deploy.yml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/web
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Setup node
      - name: Perform checks and build
        uses: actions/setup-node@v1
        with:
          version: '12.x'
      # - name: Cache dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: ${{ github.workspace }}/.next/cache
      #     key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
      # # Install deps
      # - name: Install deps
      #   run: npm install
      # # Build
      # - name: Build
      #   run: npm run build
        # env: 
        #   NEXT_PUBLIC_API_URL: ${{ secrets.API_URL }}
      # Deploy to vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-args: '--prod'